---
- name: Ensure local.conf exists
  become: true
  ansible.builtin.file:
    path: "{{ redis_path }}/local.conf"
    state: touch
    mode: "{{ redis_file_mode }}"
    owner : redis
    group: redis

- name: Ensure local.conf is included
  become: true
  ansible.builtin.lineinfile:
    path: "{{ redis_path }}/redis.conf"
    insertafter: EOF
    search_string: "include {{ redis_path }}/local.conf"
    line: "include {{ redis_path }}/local.conf"
  notify:
    - restart redis-server

- name: Copy redis config file
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ redis_path }}/local.conf"
    mode: "{{ redis_file_mode }}"
    owner : redis
    group: redis
    force: true
  with_first_found:
    - files:
        - "{{ redis_local_conf_file }}"
      skip: true
  notify:
    - restart redis-server

- name: Copy redis config template file
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ redis_path }}/local.conf"
    mode: "{{ redis_file_mode }}"
    owner : redis
    group: redis
    force: true
  with_first_found:
    - files:
        - "{{ redis_local_conf_file }}.j2"
      skip: true
  notify:
    - restart redis-server
